
name: Build loader

on: workflow_dispatch
#  repository_dispatch:
#  workflow_dispatch:
#    inputs:
#      ssh:
#        description: 'SSH connection to Actions'
#        required: false
#        default: 'false'

#  watch:
#    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build_loader:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
#    - name: Checkout
#      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install bspatch
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone --depth 1 -b develop https://github.com/jumkey/redpill-load.git redpill-load
        git clone --depth 1 -b master https://github.com/RedPill-TTG/redpill-lkm.git
        git clone --depth 1 -b DSM7.0 https://github.com/SynologyOpenSource/pkgscripts-ng.git

    - name: Compile the firmware
      id: compile
      working-directory: /workdir
      run: |
        echo 'step 1'
        cd pkgscripts-ng
        sudo ./EnvDeploy -v 7.0 -p apollolake
        export CROSS_COMPILE=/workdir/build_env/ds.apollolake-7.0/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-
        export ARCH=x86_64
        export LINUX_SRC=/workdir/build_env/ds.apollolake-7.0/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.0/build
        cd ..
        
        echo 'step 2'
        cd redpill-lkm
        make prod-v7
        cd ..
        
        echo 'step 3'
        mkdir -p redpill-load/ext/rp-lkm
        cp redpill-lkm/redpill.ko redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko

#        echo '{' > user_config.json
#        echo '  "extra_cmdline": {' >> user_config.json
         echo '    "vid": "0x1666",' >> user_config.json
         echo '    "pid": "0x0951",' >> user_config.json
#        echo '    "sn": "D3ZZZZZZZZZZZ",' >> user_config.json
#        echo '    "mac1": "021132aabbcc"' >> user_config.json
#        echo '  }' >> user_config.json
#        echo '}' >> user_config.json

        echo 'step 4'
        cd redpill-load
        sudo ./build-loader.sh 'DS918+' '7.0.1-42218'
        ls -l images
        mv images/redpill-DS918+*.img images/redpill-DS918+.img

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: Loader_firmware
        path: /workdir/redpill-load/images/redpill-DS918+.img
